src/Entity/Actor.php
<?php

namespace App\Entity;

use App\Repository\ActorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ActorRepository::class)
 */
class Actor
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstname;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birth_date;

    /**
     * @ORM\ManyToMany(targetEntity=Program::class, inversedBy="actors")
     */
    private $programs;

    public function __construct()
    {
        $this->programs = new ArrayCollection();
    }

    public function getDisplayName(): ?string
    {
        return $this->firstname . ' ' . $this->lastname;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birth_date;
    }

    public function setBirthDate(?\DateTimeInterface $birth_date): self
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    /**
     * @return Collection|Program[]
     */
    public function getPrograms(): Collection
    {
        return $this->programs;
    }

    public function addProgram(Program $program): self
    {
        if (!$this->programs->contains($program)) {
            $this->programs[] = $program;
        }

        return $this;
    }

    public function removeProgram(Program $program): self
    {
        $this->programs->removeElement($program);

        return $this;
    }
}

src/Form/ActorType.php
<?php

namespace App\Form;

use App\Entity\Actor;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ActorType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('lastname')
            ->add('firstname')
            ->add('birth_date')
            ->add('programs', null, ['choice_label' => 'title'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Actor::class,
        ]);
    }
}

src/Controller/ActorController.php
<?php

namespace App\Controller;

use App\Entity\Actor;
use App\Form\ActorType;
use App\Repository\ActorRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/actor")
 */
class ActorController extends AbstractController
{
    /**
     * @Route("/", name="actor_index", methods={"GET"})
     */
    public function index(ActorRepository $actorRepository): Response
    {
        return $this->render('actor/index.html.twig', [
            'actors' => $actorRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="actor_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $actor = new Actor();
        $form = $this->createForm(ActorType::class, $actor);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($actor);
            $entityManager->flush();

            return $this->redirectToRoute('actor_index');
        }

        return $this->render('actor/new.html.twig', [
            'actor' => $actor,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="actor_show", methods={"GET"})
     */
    public function show(Actor $actor): Response
    {
        return $this->render('actor/show.html.twig', [
            'actor' => $actor,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="actor_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Actor $actor): Response
    {
        $form = $this->createForm(ActorType::class, $actor);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('actor_index');
        }

        return $this->render('actor/edit.html.twig', [
            'actor' => $actor,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="actor_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Actor $actor): Response
    {
        if ($this->isCsrfTokenValid('delete'.$actor->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($actor);
            $entityManager->flush();
        }

        return $this->redirectToRoute('actor_index');
    }
}

templates/actor/_delete_form.html.twig
<form method="post" action="{{ path('actor_delete', {'id': actor.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ actor.id) }}">
    <button class="btn">Delete</button>
</form>

templates/actor/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/actor/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Actor{% endblock %}

{% block body %}
    <h1>Edit Actor</h1>

    {{ include('actor/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('actor_index') }}">back to list</a>

    {{ include('actor/_delete_form.html.twig') }}
{% endblock %}

templates/actor/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Actor index{% endblock %}

{% block body %}
    <h1>Actor index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Lastname</th>
                <th>Firstname</th>
                <th>Birth_date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for actor in actors %}
            <tr>
                <td>{{ actor.id }}</td>
                <td>{{ actor.lastname }}</td>
                <td>{{ actor.firstname }}</td>
                <td>{{ actor.birthDate ? actor.birthDate|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('actor_show', {'id': actor.id}) }}">show</a>
                    <a href="{{ path('actor_edit', {'id': actor.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('actor_new') }}">Create new</a>
{% endblock %}

templates/actor/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Actor{% endblock %}

{% block body %}
    <h1>Create new Actor</h1>

    {{ include('actor/_form.html.twig') }}

    <a href="{{ path('actor_index') }}">back to list</a>
{% endblock %}

templates/actor/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Actor
{% endblock %}

{% block body %}
	<h1>Actor</h1>

	<table class="table">
		<tbody>
			<tr>
				<th>Id</th>
				<td>{{ actor.id }}</td>
			</tr>
			<tr>
				<th>Lastname</th>
				<td>{{ actor.lastname }}</td>
			</tr>
			<tr>
				<th>Firstname</th>
				<td>{{ actor.firstname }}</td>
			</tr>
			<tr>
				<th>Birth_date</th>
				<td>{{ actor.birthDate ? actor.birthDate|date('Y-m-d') : '' }}</td>
			</tr>
		</tbody>
	</table>

	<ul>
		{% for program in actor.programs %}
			<li>
				<a href="{{path("program_show", {id: program.id})}}">
					{{ program.title }}
				</a>
			</li>
		{% else %}
			<li>Aucun acteur pour cette série</li>
		{% endfor %}
	</ul>

	<a href="{{ path('actor_index') }}">back to list</a>

	<a href="{{ path('actor_edit', {'id': actor.id}) }}">edit</a>

	{{ include('actor/_delete_form.html.twig') }}
{% endblock %}